# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('activityType', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityID', models.IntegerField(default=0)),
                ('recordID', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CancerSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField()),
                ('gender', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('staffGroup', models.CharField(default='', max_length=50)),
                ('centreLocation', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffMember', models.CharField(default='', max_length=50)),
                ('recordID', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vType', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vType', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
