# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('natureOfVisit', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='VisitNature',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activityID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activityType',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='activity_record',
            old_name='activityID',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='activity_record',
            old_name='recordID',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recordID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='staffmember_record',
            old_name='recordID',
            new_name='record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='gender',
        ),
        migrations.AlterField(
            model_name='activity_record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cancersite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffmember_record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitortype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
