# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEndApp', '0003_auto_20161105_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='centreLocation',
        ),
    ]
