# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEndApp', '0004_auto_20161105_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('staffGroup', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='activity_record',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='age',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='cancersite',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='centre',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='journeystage',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='natureofvisit',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='staffmember_record',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='visitortype',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='visittype',
            old_name='id',
            new_name='ID',
        ),
    ]
