# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEndApp', '0005_auto_20161105_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorType',
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
