# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEndApp', '0007_remove_record_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity_Record',
        ),
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='CancerSite',
        ),
        migrations.DeleteModel(
            name='Centre',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='JourneyStage',
        ),
        migrations.DeleteModel(
            name='NatureOfVisit',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='StaffGroup',
        ),
        migrations.DeleteModel(
            name='StaffMember_Record',
        ),
        migrations.DeleteModel(
            name='VisitType',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ID',
        ),
        migrations.AddField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myBackEndApp.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='cancerSite',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='journeyStage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='natureOfVisit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='person',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='visitType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myBackEndApp.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
