# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBackEndApp', '0010_auto_20161106_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='record',
        ),
    ]
